version: '2'

services:
  app:
    image: mczabaj/line_server:build
    cpu_shares: 896
    mem_limit: 768m
    restart: always
    ports:
      - "80:80"
    volumes:
      - config:/config
    environment:
      CONFIG_PATH_IN: "/config/config.edn"
      CONFIG_PATH: "/usr/src/app/config.edn"
      PORT: 80
      APP_START_COMMAND: "java -jar -Dconf=/usr/src/app/config.edn /usr/src/app/target/uberjar/line_server.jar"

# Define shared volumes
volumes:
  config: {}
